id = "10845"
url = "https://www.acmicpc.net/problem/10845"
title = "큐"

[[examples]]
input = "15\npush 1\npush 2\nfront\nback\nsize\nempty\npop\npop\npop\nsize\nempty\npop\npush 3\nempty\nfront\n"
output = "1\n2\n2\n0\n1\n2\n-1\n0\n1\n-1\n0\n3\n"
