id = "2798"
url = "https://www.acmicpc.net/problem/2798"
title = "블랙잭"

[[examples]]
input = "5 21\n5 6 7 8 9\n"
output = "21\n"

[[examples]]
input = "10 500\n93 181 245 214 315 36 185 138 216 295\n"
output = "497\n"
