id = "10828"
url = "https://www.acmicpc.net/problem/10828"
title = "스택"

[[examples]]
input = "14\npush 1\npush 2\ntop\nsize\nempty\npop\npop\npop\nsize\nempty\npop\npush 3\nempty\ntop\n"
output = "2\n2\n0\n2\n1\n-1\n0\n1\n-1\n0\n3\n"

[[examples]]
input = "7\npop\ntop\npush 123\ntop\npop\ntop\npop\n"
output = "-1\n-1\n123\n123\n-1\n-1\n"
